### ISSUE TITLE
Como faço para pegar a autorização no desenvolvimento?

### ISSUE THREAD

**Issue by javacunha** [Sage/sageone_br_nfe_documentacao_api#19]
Peguei o code após a publicação de uma página no meu site.
Como fazer isso no ambiente de desenvolvimento?

Meu cliente que usa minha aplicação terá que logar toda vez no site de vcs para permitir que meu sistema emita nota fiscal?

**Comment by luizhpcamargo** [comment]
Você ver alguns exemplos de uso na wiki de como pegar o code.
Você pode fazer a chamada utilizando o grant_type com refresh_token que gerará um novo token para a conexão, pode colocar uma condicional de que se o token está expirado chamar a atualização para pegar um novo.

**Comment by javacunha** [comment]
Luiz,

Fiz a chamada no post no endereço e os parametros e retorna o erro abaixo:

Onde yyy é o código que peguei na mão após dar permissão após o login.

urlWebService: https://api.sageone.com/oauth2/token
parametros: client_id=xxxx&client_secret=xxx&code=yyyy&grant_type=refresh_token&redirect_uri=https://app.sisdanca.com.br/sistema/sageone/calback.jsp

Erro:
java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sageone.com/oauth2/token
Erro na integração de conta: {"error":"invalid_grant"}

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at br.es.veweb.base.sageone.UtilJson.post(UtilJson.java:183)
	at br.es.veweb.base.sageone.IntegracaoSageOne.main(IntegracaoSageOne.java:23)
Exception in thread "main" java.lang.Exception: {"error":"invalid_grant"}

	at br.es.veweb.base.sageone.UtilJson.post(UtilJson.java:197)
	at br.es.veweb.base.sageone.IntegracaoSageOne.main(IntegracaoSageOne.java:23)
Java Result: 1

**Comment by javacunha** [comment]
Já tentei também com: authorization_code no grant_type
